[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY = ""

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    version = "5.9.4"

